AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD Demo Lambda
Resources:
  CDDemoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: workoutData.handler
      Runtime: nodejs8.10
      CodeUri: ./
      Description: 'Lambda function for CD Demo'
      MemorySize: 128
      Timeout: 30
      # Role: 'arn:aws:iam::077497884784:role/cloudformationServiceRole'
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /getazs
            Method: get
      Environment:
        Variables:
          REGION: ap-south-1